"""
Learnova End-to-End Tests
Run with: pytest tests/test_learnova.py -v
"""

import os
import pathlib

import pytest

from learnova.parsers.ppt_parser import parse_ppt, ParsedDocument
from learnova.parsers.pdf_parser import parse_pdf
from learnova.rag.chunker import chunk_parsed_data
from learnova.ai.improver import improve_chunks
from learnova.ai.quiz_gen import generate_quizzes
from learnova.scoring.scorer import score_slide, score_all_slides

# The PPTX fixture is generated by `python scripts/generate_sample.py` and is
# committed, so the PPT parser test runs for real rather than skipping.
_FIXTURES = pathlib.Path(__file__).resolve().parent / "fixtures"
PPT_PATH = str(_FIXTURES / "sample_test_presentation.pptx")
# No PDF fixture is committed (they are large); drop one here to enable the test.
PDF_PATH = str(_FIXTURES / "sample_test_document.pdf")


# ═══════════════════════════════════════════════════════════════════════════════
# Unit Tests
# ═══════════════════════════════════════════════════════════════════════════════

class TestPPTParser:
    @pytest.mark.skipif(not os.path.exists(PPT_PATH), reason="PPT file not found")
    def test_ppt_parser(self):
        doc = parse_ppt(PPT_PATH)
        assert isinstance(doc, ParsedDocument), "Should return ParsedDocument"
        slides = doc.slide_units
        assert len(slides) > 0, "Should have at least one slide"
        for slide in slides:
            assert hasattr(slide, "id"), "Missing 'id' attribute"
            assert hasattr(slide, "title"), "Missing 'title' attribute"
            assert hasattr(slide, "text"), "Missing 'text' attribute"
        print(f"\n✅ PPT Parser: {len(slides)} slides extracted")


class TestPDFParser:
    @pytest.mark.skipif(not os.path.exists(PDF_PATH), reason="PDF file not found")
    def test_pdf_parser(self):
        doc = parse_pdf(PDF_PATH)
        assert isinstance(doc, ParsedDocument), "Should return ParsedDocument"
        slides = doc.slide_units
        assert len(slides) > 0, "Should have at least one page"
        for page in slides:
            assert hasattr(page, "id"), "Missing 'id' attribute"
            assert hasattr(page, "title"), "Missing 'title' attribute"
            assert hasattr(page, "text"), "Missing 'text' attribute"
        print(f"\n✅ PDF Parser: {len(slides)} pages extracted")


class TestChunker:
    def test_chunker_with_ppt_format(self):
        mock_parsed = [
            {"slide": 1, "title": "Intro", "content": ["Hello world"] * 20},
            {"slide": 2, "title": "Details", "content": ["Some details"]},
        ]
        chunks = chunk_parsed_data(mock_parsed)
        assert isinstance(chunks, list)
        assert len(chunks) > 0
        for chunk in chunks:
            assert "id" in chunk, "Missing 'id' key"
            assert "title" in chunk, "Missing 'title' key"
            assert "text" in chunk, "Missing 'text' key"
            assert "source" in chunk, "Missing 'source' key"
        print(f"\n✅ Chunker: {len(chunks)} chunks created")

    def test_chunker_with_pdf_format(self):
        mock_parsed = [
            {"page": 1, "heading": "Chapter 1", "content": "Some long text " * 30},
        ]
        chunks = chunk_parsed_data(mock_parsed)
        assert isinstance(chunks, list)
        assert len(chunks) > 0
        for chunk in chunks:
            word_count = len(chunk["text"].split())
            assert word_count <= 180, f"Chunk exceeds 180 words: {word_count}"
        print(f"\n✅ Chunker (PDF): {len(chunks)} chunks created")


class TestImprover:
    @pytest.mark.skipif(
        not os.getenv("GROQ_API_KEY"),
        reason="GROQ_API_KEY not set",
    )
    def test_improver(self):
        mock_chunks = [
            {"id": 1, "title": "Test Slide", "text": "This is a test slide about machine learning.", "source": 1},
        ]
        results = improve_chunks(mock_chunks)
        assert isinstance(results, list)
        assert len(results) == 1
        improved = results[0]["improved"]
        assert "title" in improved, "Missing 'title' in improved"
        assert "bullets" in improved, "Missing 'bullets' in improved"
        assert "takeaway" in improved, "Missing 'takeaway' in improved"
        print(f"\n✅ Improver: Improved slide title = '{improved['title']}'")


class TestQuizGen:
    @pytest.mark.skipif(
        not os.getenv("GROQ_API_KEY"),
        reason="GROQ_API_KEY not set",
    )
    def test_quiz_gen(self):
        mock_improved = [
            {
                "original": {"id": i, "title": f"Slide {i}", "text": "Content", "source": i},
                "improved": {
                    "title": f"Slide {i}",
                    "bullets": ["Machine learning is a subset of AI",
                                "It learns from data patterns",
                                "Used in many industries"],
                    "takeaway": "ML is powerful",
                },
            }
            for i in range(1, 4)
        ]
        quizzes = generate_quizzes(mock_improved)
        assert isinstance(quizzes, list)
        if quizzes:
            q = quizzes[0]
            assert "question" in q, "Missing 'question'"
            assert "options" in q, "Missing 'options'"
            assert "correct" in q, "Missing 'correct'"
            assert len(q["correct"]) == 1, "Correct answer should be normalized to 1 character"
            print(f"\n✅ Quiz Gen: '{q['question'][:60]}...'")
        else:
            print("\n⚠️ Quiz Gen: No quizzes generated")


class TestScorer:
    def test_score_slide(self):
        mock_improved = {
            "title": "Introduction to Machine Learning",
            "bullets": [
                "ML is a subset of artificial intelligence",
                "It learns patterns from data",
                "Supervised and unsupervised learning",
                "Used in healthcare, finance, and tech",
            ],
            "takeaway": "Machine learning helps automate decisions using data",
        }
        result = score_slide(mock_improved)
        assert "score" in result
        assert "breakdown" in result
        assert 0 <= result["score"] <= 100, f"Score out of range: {result['score']}"
        breakdown = result["breakdown"]
        for key in ["text_density", "bullet_count", "title_quality", "has_takeaway", "readability"]:
            assert key in breakdown, f"Missing breakdown key: {key}"
        print(f"\n✅ Scorer: Score = {result['score']}/100, Breakdown = {breakdown}")

    def test_score_all_slides(self):
        mock_results = [
            {
                "original": {"id": 1, "title": "T", "text": "X", "source": 1},
                "improved": {
                    "title": "Good Title Here",
                    "bullets": ["Point one", "Point two", "Point three"],
                    "takeaway": "Key insight",
                },
            }
        ]
        result = score_all_slides(mock_results)
        assert "slide_scores" in result
        assert "overall_score" in result
        assert len(result["slide_scores"]) == 1
        print(f"\n✅ Scorer (all): Overall = {result['overall_score']}/100")
