"""
Learnova Modern Themed PPTX Builder
Generates PPTX decks with dynamic visual layouts (Flowcharts, Tables, Metric Cards, Quizzes)
and embeds PowerPoint OpenXML slide transition animations.
"""

import io
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.xmlchemy import OxmlElement

from utils.theme_engine import get_theme, auto_detect_theme, select_slide_layout, ColorPalette, THEMES, LAYOUT_STYLES

def SubElement(parent, tagname, **kwargs):
    element = OxmlElement(tagname)
    element.attrib.update(kwargs)
    parent.append(element)
    return element

def _add_slide_transition(slide):
    """Inject OpenXML transition tag for smooth slide entrance."""
    try:
        slide_elem = slide._element
        transition = OxmlElement('p:transition')
        transition.set('spd', 'med')
        push = OxmlElement('p:push')
        push.set('dir', 'l')
        transition.append(push)
        slide_elem.append(transition)
    except Exception:
        pass

def _add_header_bar(slide, title_text: str, theme: ColorPalette):
    header_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.33), Inches(1.1))
    header_bar.fill.solid()
    header_bar.fill.fore_color.rgb = theme.primary_rgb
    header_bar.line.fill.background()

    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.1), Inches(12.3), Inches(0.9))
    tf = title_box.text_frame
    tf.word_wrap = True
    tf.text = title_text
    p = tf.paragraphs[0]
    p.font.size = Pt(28)
    p.font.bold = True
    p.font.color.rgb = theme.accent_rgb

def _add_takeaway_bar(slide, takeaway_text: str, theme: ColorPalette):
    if not takeaway_text:
        return
    tkw_box = slide.shapes.add_textbox(Inches(0.5), Inches(6.0), Inches(12.3), Inches(1.1))
    tkw_box.fill.solid()
    tkw_box.fill.fore_color.rgb = theme.primary_rgb
    tkw_box.line.color.rgb = theme.accent_rgb
    tkw_box.line.width = Pt(2)

    ttk = tkw_box.text_frame
    ttk.word_wrap = True
    tp = ttk.paragraphs[0]
    tp.text = f"💡 Key Takeaway: {takeaway_text}"
    tp.font.color.rgb = theme.text_rgb
    tp.font.size = Pt(15)
    tp.font.bold = True

def build_pptx(slides_data: list[dict], topic_title: str = "Learnova Presentation", theme_id: str = "auto") -> bytes:
    if theme_id == "auto":
        theme = auto_detect_theme(topic_title)
    else:
        theme = get_theme(theme_id)

    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.33), Inches(7.5)

    # ── Title slide ───────────────────────────────────────────────────────────
    title_slide = prs.slides.add_slide(prs.slide_layouts[6])
    title_slide.background.fill.solid()
    title_slide.background.fill.fore_color.rgb = theme.primary_rgb

    accent = title_slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(3.5), Inches(13.33), Inches(0.12))
    accent.fill.solid()
    accent.fill.fore_color.rgb = theme.accent_rgb
    accent.line.fill.background()

    tf1 = title_slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(11), Inches(1.8)).text_frame
    tf1.text = topic_title.upper()
    tf1.paragraphs[0].font.size = Pt(48)
    tf1.paragraphs[0].font.bold = True
    tf1.paragraphs[0].font.color.rgb = theme.accent_rgb
    tf1.paragraphs[0].alignment = PP_ALIGN.CENTER

    tf2 = title_slide.shapes.add_textbox(Inches(1), Inches(3.8), Inches(11), Inches(1)).text_frame
    tf2.text = f"Generated by Learnova AI Engine • Theme: {theme.name}"
    tf2.paragraphs[0].font.size = Pt(20)
    tf2.paragraphs[0].font.color.rgb = theme.text_rgb
    tf2.paragraphs[0].alignment = PP_ALIGN.CENTER

    # ── Content slides ────────────────────────────────────────────────────────
    prev_style = None
    for idx, data in enumerate(slides_data):
        orig = data.get("original", {})
        imp = data.get("improved", {})
        if not isinstance(imp, dict):
            imp = {}

        slide = prs.slides.add_slide(prs.slide_layouts[6])
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = theme.bg_rgb
        _add_slide_transition(slide)

        layout_type = imp.get("layout_type", "MINIMAL_TEXT").upper()
        style_pattern = select_slide_layout(idx, layout_type, prev_style)
        prev_style = style_pattern

        title_text = imp.get("title", orig.get("title", "Presentation Slide"))
        takeaway_text = imp.get("takeaway", "").strip()

        _add_header_bar(slide, title_text, theme)

        # ── 1. TABLE LAYOUT ──────────────────────────────────────────────────
        if layout_type == "TABLE" and "table_headers" in imp and "table_rows" in imp:
            headers = imp.get("table_headers", [])
            rows = imp.get("table_rows", [])
            if headers and rows:
                num_rows = len(rows) + 1
                num_cols = len(headers)
                tbl_shape = slide.shapes.add_table(num_rows, num_cols, Inches(0.8), Inches(1.4), Inches(11.73), Inches(4.3))
                tbl = tbl_shape.table

                # Format Header Row
                for c_idx, h_text in enumerate(headers):
                    cell = tbl.cell(0, c_idx)
                    cell.text = str(h_text)
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = theme.primary_rgb
                    for p in cell.text_frame.paragraphs:
                        p.font.color.rgb = theme.accent_rgb
                        p.font.bold = True
                        p.font.size = Pt(14)

                # Format Data Rows
                for r_idx, row_vals in enumerate(rows):
                    for c_idx, val in enumerate(row_vals):
                        if c_idx < num_cols:
                            cell = tbl.cell(r_idx + 1, c_idx)
                            cell.text = str(val)
                            cell.fill.solid()
                            cell.fill.fore_color.rgb = theme.card_bg_rgb
                            for p in cell.text_frame.paragraphs:
                                p.font.size = Pt(12)
                                p.font.color.rgb = theme.text_rgb

        # ── 2. METRIC STAT CALLOUT LAYOUT ─────────────────────────────────────
        elif layout_type == "METRIC":
            metric_val = imp.get("metric_value", "100%")
            metric_lbl = imp.get("metric_label", title_text)
            metric_desc = imp.get("metric_desc", takeaway_text)

            box = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(2), Inches(1.6), Inches(9.33), Inches(4.0))
            box.fill.solid()
            box.fill.fore_color.rgb = theme.primary_rgb
            box.line.color.rgb = theme.accent_rgb
            box.line.width = Pt(4)

            mtf = box.text_frame
            mtf.word_wrap = True

            p1 = mtf.paragraphs[0]
            p1.text = metric_val
            p1.font.size = Pt(72)
            p1.font.bold = True
            p1.font.color.rgb = theme.accent_rgb
            p1.alignment = PP_ALIGN.CENTER

            p2 = mtf.add_paragraph()
            p2.text = metric_lbl.upper()
            p2.font.size = Pt(24)
            p2.font.bold = True
            p2.font.color.rgb = theme.subtext_rgb
            p2.alignment = PP_ALIGN.CENTER

            p3 = mtf.add_paragraph()
            p3.text = metric_desc
            p3.font.size = Pt(16)
            p3.font.color.rgb = theme.text_rgb
            p3.alignment = PP_ALIGN.CENTER

        # ── 3. INTERLEAVED QUIZ CHECKPOINT ────────────────────────────────────
        elif layout_type == "QUIZ":
            q_text = imp.get("question", "Checkpoint Question")
            options = imp.get("options", [])
            correct_opt = imp.get("correct", "A")

            qbox = slide.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(12.3), Inches(1.2))
            qtf = qbox.text_frame
            qtf.word_wrap = True
            qp = qtf.paragraphs[0]
            qp.text = f"❓ Question: {q_text}"
            qp.font.size = Pt(20)
            qp.font.bold = True
            qp.font.color.rgb = theme.primary_rgb

            card_positions = [
                (Inches(0.5), Inches(2.7)),
                (Inches(6.8), Inches(2.7)),
                (Inches(0.5), Inches(4.3)),
                (Inches(6.8), Inches(4.3)),
            ]
            for idx, opt_text in enumerate(options[:4]):
                c_left, c_top = card_positions[idx]
                card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, c_left, c_top, Inches(6.0), Inches(1.3))
                card.fill.solid()
                card.fill.fore_color.rgb = theme.primary_rgb if str(opt_text).startswith(correct_opt) else theme.card_bg_rgb
                card.line.color.rgb = theme.primary_rgb
                card.line.width = Pt(2)

                ctf = card.text_frame
                ctf.word_wrap = True
                cp = ctf.paragraphs[0]
                cp.text = str(opt_text)
                cp.font.size = Pt(16)
                cp.font.bold = True
                cp.font.color.rgb = theme.accent_rgb if str(opt_text).startswith(correct_opt) else theme.text_rgb

        # ── 4. FLOWCHART / PROCESS STEP CARDS ──────────────────────────────────
        elif layout_type == "FLOWCHART":
            mermaid_code = imp.get("mermaid_code", "")
            bullets = imp.get("bullets", [])

            steps = bullets if bullets else ["Step 1: Initiation", "Step 2: Execution", "Step 3: Completion"]
            step_count = len(steps[:4])
            card_w = Inches(11.5 / max(1, step_count))

            for idx, step_text in enumerate(steps[:4]):
                c_left = Inches(0.8) + idx * (card_w + Inches(0.2))
                card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, c_left, Inches(1.8), card_w, Inches(3.8))
                card.fill.solid()
                card.fill.fore_color.rgb = theme.primary_rgb if idx % 2 == 0 else theme.card_bg_rgb
                card.line.color.rgb = theme.primary_rgb
                card.line.width = Pt(2)

                ctf = card.text_frame
                ctf.word_wrap = True

                sp1 = ctf.paragraphs[0]
                sp1.text = f"STEP {idx + 1}"
                sp1.font.size = Pt(14)
                sp1.font.bold = True
                sp1.font.color.rgb = theme.accent_rgb if idx % 2 == 0 else theme.primary_rgb

                sp2 = ctf.add_paragraph()
                sp2.text = step_text
                sp2.font.size = Pt(16)
                sp2.font.color.rgb = theme.text_rgb

        # ── 5. CARD GRID LAYOUT ──────────────────────────────────────────────
        elif layout_type == "CARD_GRID":
            bullets = imp.get("bullets", [])
            items = bullets[:4] if bullets else ["Pillar 1", "Pillar 2", "Pillar 3"]
            count = len(items)
            card_w = Inches(11.5 / max(1, count))

            for idx, item_text in enumerate(items):
                c_left = Inches(0.8) + idx * (card_w + Inches(0.2))
                card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, c_left, Inches(1.8), card_w, Inches(3.8))
                card.fill.solid()
                card.fill.fore_color.rgb = theme.card_bg_rgb
                card.line.color.rgb = theme.primary_rgb
                card.line.width = Pt(2)

                ctf = card.text_frame
                ctf.word_wrap = True

                sp1 = ctf.paragraphs[0]
                sp1.text = f"PILLAR {idx + 1}"
                sp1.font.size = Pt(14)
                sp1.font.bold = True
                sp1.font.color.rgb = theme.primary_rgb

                sp2 = ctf.add_paragraph()
                sp2.text = item_text
                sp2.font.size = Pt(15)
                sp2.font.color.rgb = theme.text_rgb

        # ── 6. DEFAULT / MINIMAL TEXT + IMAGE COLUMN LAYOUT ───────────────────
        else:
            has_img = "image" in orig and orig["image"] and orig["image"].get("bytes")
            text_left = Inches(0.5)
            text_width = Inches(7.2) if has_img else Inches(12.3)

            bullets = imp.get("bullets", [])
            body_box = slide.shapes.add_textbox(text_left, Inches(1.3), text_width, Inches(4.5))
            btf = body_box.text_frame
            btf.word_wrap = True

            for i, bullet in enumerate(bullets):
                clean_b = bullet.replace("▪", "").strip()
                p = btf.add_paragraph() if i > 0 else btf.paragraphs[0]
                p.text = clean_b
                p.font.size = Pt(18)
                p.font.color.rgb = theme.text_rgb
                p.space_after = Pt(10)
                pPr = p._p.get_or_add_pPr()
                SubElement(pPr, "a:buChar", char="•")

            if has_img and orig["image"].get("bytes"):
                try:
                    slide.shapes.add_picture(
                        io.BytesIO(orig["image"]["bytes"]),
                        Inches(7.9), Inches(1.3), width=Inches(4.9)
                    )
                except Exception:
                    pass

        _add_takeaway_bar(slide, takeaway_text, theme)

    # ── Closing slide ─────────────────────────────────────────────────────────
    end_slide = prs.slides.add_slide(prs.slide_layouts[6])
    end_slide.background.fill.solid()
    end_slide.background.fill.fore_color.rgb = theme.primary_rgb
    _add_slide_transition(end_slide)

    accent2 = end_slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(3.5), Inches(13.33), Inches(0.12))
    accent2.fill.solid()
    accent2.fill.fore_color.rgb = theme.accent_rgb

    tfe = end_slide.shapes.add_textbox(Inches(1), Inches(2.8), Inches(11), Inches(1.5)).text_frame
    tfe.text = "THANK YOU"
    tfe.paragraphs[0].font.size = Pt(60)
    tfe.paragraphs[0].font.bold = True
    tfe.paragraphs[0].font.color.rgb = theme.accent_rgb
    tfe.paragraphs[0].alignment = PP_ALIGN.CENTER

    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.getvalue()