import io
import textwrap
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.xmlchemy import OxmlElement

def SubElement(parent, tagname, **kwargs):
    element = OxmlElement(tagname)
    element.attrib.update(kwargs)
    parent.append(element)
    return element

_Navy = RGBColor(30, 39, 97)
_IceBlue = RGBColor(202, 220, 252)
_White = RGBColor(255, 255, 255)
_LightGray = RGBColor(245, 245, 250)
_AccentGreen = RGBColor(204, 255, 0)

def build_pptx(slides_data: list[dict], topic_title: str = "Learnova Presentation") -> bytes:
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.33), Inches(7.5)

    # ── Title slide ───────────────────────────────────────────────────────────
    title_slide = prs.slides.add_slide(prs.slide_layouts[6])
    title_slide.background.fill.solid()
    title_slide.background.fill.fore_color.rgb = _Navy

    # Accent bar (neon green strip)
    accent = title_slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(3.5), Inches(13.33), Inches(0.12))
    accent.fill.solid()
    accent.fill.fore_color.rgb = _AccentGreen
    accent.line.fill.background()

    tf1 = title_slide.shapes.add_textbox(Inches(1), Inches(1.5), Inches(11), Inches(1.8)).text_frame
    tf1.text = topic_title.upper()
    tf1.paragraphs[0].font.size = Pt(52)
    tf1.paragraphs[0].font.bold = True
    tf1.paragraphs[0].font.color.rgb = _IceBlue
    tf1.paragraphs[0].alignment = PP_ALIGN.CENTER

    tf2 = title_slide.shapes.add_textbox(Inches(1), Inches(3.8), Inches(11), Inches(1)).text_frame
    tf2.text = "Generated by Learnova AI"
    tf2.paragraphs[0].font.size = Pt(22)
    tf2.paragraphs[0].font.color.rgb = _White
    tf2.paragraphs[0].alignment = PP_ALIGN.CENTER

    # ── Content slides ────────────────────────────────────────────────────────
    for data in slides_data:
        orig = data.get("original", {})
        imp = data.get("improved", {})

        if not isinstance(imp, dict):
            imp = {}

        slide = prs.slides.add_slide(prs.slide_layouts[6])
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = _LightGray

        img_bytes = None
        img_desc = None
        has_img = "image" in orig and orig["image"] and orig["image"].get("bytes")
        if has_img:
            img_bytes = orig["image"]["bytes"]
            img_desc = orig["image"].get("description", "")

        # ── Layout: LEFT side for text, RIGHT side for image (if any) ─────────
        if has_img:
            # Text column: left 7.5 inches
            text_left = Inches(0.5)
            text_width = Inches(7.2)
            img_left = Inches(7.9)
            img_col_width = Inches(4.9)
        else:
            # Full width text
            text_left = Inches(0.5)
            text_width = Inches(12.3)

        # ── Navy header bar ───────────────────────────────────────────────────
        header_bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.33), Inches(1.2))
        header_bar.fill.solid()
        header_bar.fill.fore_color.rgb = _Navy
        header_bar.line.fill.background()

        # ── Title text ────────────────────────────────────────────────────────
        title_text = imp.get("title", orig.get("title", "Presentation Slide"))
        title_box = slide.shapes.add_textbox(text_left, Inches(0.1), text_width, Inches(1.0))
        tf = title_box.text_frame
        tf.word_wrap = True
        tf.text = title_text
        p = tf.paragraphs[0]
        p.font.size = Pt(30)
        p.font.bold = True
        p.font.color.rgb = _White

        # ── Bullet points ─────────────────────────────────────────────────────
        bullets = imp.get("bullets", [])
        body_box = slide.shapes.add_textbox(text_left, Inches(1.3), text_width, Inches(4.2))
        btf = body_box.text_frame
        btf.word_wrap = True

        for i, bullet in enumerate(bullets):
            clean_b = bullet.replace("â–ª", "").replace("▪", "").strip()
            p = btf.add_paragraph() if i > 0 else btf.paragraphs[0]
            p.text = clean_b
            p.font.size = Pt(18)
            p.font.color.rgb = RGBColor(20, 20, 20)
            p.space_after = Pt(10)
            p.level = 0

            # Real PPTX bullet character
            pPr = p._p.get_or_add_pPr()
            SubElement(pPr, "a:buChar", char="•")
            pPr.set("marL", "342900")
            pPr.set("indent", "-342900")

        # ── Key Takeaway bar ──────────────────────────────────────────────────
        takeaway = imp.get("takeaway", "").strip()
        if takeaway:
            tkw_box = slide.shapes.add_textbox(text_left, Inches(5.65), text_width, Inches(1.4))
            tkw_tf_fill = tkw_box
            tkw_box.fill.solid()
            tkw_box.fill.fore_color.rgb = _Navy
            tkw_box.line.color.rgb = _AccentGreen
            tkw_box.line.width = Pt(2)

            ttk = tkw_box.text_frame
            ttk.word_wrap = True
            tp = ttk.paragraphs[0]
            tp.text = f"💡 Key Takeaway: {takeaway}"
            tp.font.color.rgb = _White
            tp.font.size = Pt(16)
            tp.font.bold = True

        # ── Image panel (right side) ──────────────────────────────────────────
        if has_img and img_bytes:
            try:
                # Image fills the right column, leaving room for description
                desc_height = Inches(0.9) if img_desc else Inches(0)
                img_top = Inches(1.25)
                img_area_height = Inches(7.5) - img_top - desc_height - Inches(0.2)

                # Add the image - let python-pptx figure out aspect ratio
                pic = slide.shapes.add_picture(
                    io.BytesIO(img_bytes),
                    img_left,
                    img_top,
                    width=img_col_width,
                )

                # Clamp height to available area
                if pic.height > img_area_height:
                    ratio = img_area_height / pic.height
                    pic.height = int(img_area_height)
                    pic.width = int(pic.width * ratio)
                    # Re-center horizontally in column
                    pic.left = int(img_left + (img_col_width - pic.width) / 2)

                # ── AI image description caption ───────────────────────────────
                if img_desc:
                    cap_top = img_top + pic.height + Inches(0.1)
                    cap_box = slide.shapes.add_textbox(img_left, cap_top, img_col_width, desc_height)
                    cap_box.fill.solid()
                    cap_box.fill.fore_color.rgb = _IceBlue
                    cap_box.line.color.rgb = _Navy
                    cap_box.line.width = Pt(1)
                    cp = cap_box.text_frame
                    cp.word_wrap = True
                    cp_p = cp.paragraphs[0]
                    # Truncate description for caption
                    cap_text = img_desc[:200] + ("…" if len(img_desc) > 200 else "")
                    cp_p.text = f"🖼️ {cap_text}"
                    cp_p.font.size = Pt(10)
                    cp_p.font.color.rgb = _Navy
                    cp_p.font.italic = True

            except Exception:
                pass

    # ── Closing slide ─────────────────────────────────────────────────────────
    end_slide = prs.slides.add_slide(prs.slide_layouts[6])
    end_slide.background.fill.solid()
    end_slide.background.fill.fore_color.rgb = _Navy

    accent2 = end_slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(3.5), Inches(13.33), Inches(0.12))
    accent2.fill.solid()
    accent2.fill.fore_color.rgb = _AccentGreen
    accent2.line.fill.background()

    tfe = end_slide.shapes.add_textbox(Inches(1), Inches(2.8), Inches(11), Inches(1.5)).text_frame
    tfe.text = "THANK YOU"
    tfe.paragraphs[0].font.size = Pt(64)
    tfe.paragraphs[0].font.bold = True
    tfe.paragraphs[0].font.color.rgb = _IceBlue
    tfe.paragraphs[0].alignment = PP_ALIGN.CENTER

    tfe2 = end_slide.shapes.add_textbox(Inches(1), Inches(4.2), Inches(11), Inches(0.8)).text_frame
    tfe2.text = "Generated by Learnova AI"
    tfe2.paragraphs[0].font.size = Pt(20)
    tfe2.paragraphs[0].font.color.rgb = _White
    tfe2.paragraphs[0].alignment = PP_ALIGN.CENTER

    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output.getvalue()