"""
Learnova Web Deck Builder Module
Generates a standalone, responsive 60fps HTML5 presentation powered by Reveal.js and Mermaid.js.
Supports live interactive quizzes, flowcharts, tables, metric cards, and smooth slide transitions.
"""

import html
import re
import json
from learnova.rendering.theme_engine import (
    get_theme, auto_detect_theme, select_slide_layout, resolve_theme,
    readable_text_hex, THEMES,
)

def _inline_quiz_html(quiz: dict, theme) -> str:
    """Render a checkpoint question as a band at the foot of a web-deck slide."""
    if not quiz:
        return ""
    options = [str(o).strip() for o in (quiz.get("options") or []) if str(o).strip()][:4]
    letters = "ABCD"
    chips = "".join(
        f'<div style="flex:1 1 0;min-width:0;border:1px solid {theme.primary_hex};'
        f'background:{theme.bg_hex};color:{theme.text_hex};padding:6px 10px;'
        f'font-size:0.62em;border-radius:6px;">'
        f'<b>{letters[i]}.</b> {html.escape(re.sub(r"^\s*[A-Da-d][).:]\s*", "", opt))}</div>'
        for i, opt in enumerate(options)
    )
    return f"""
    <div style="margin-top:18px;border:2px solid {theme.accent_hex};
                background:{theme.card_bg_hex};border-radius:10px;padding:12px 14px;">
      <div style="color:{theme.text_hex};font-weight:700;font-size:0.72em;margin-bottom:8px;">
        Q{quiz.get('index', 1)}. {html.escape(str(quiz.get('question', '')))}
      </div>
      <div style="display:flex;gap:8px;">{chips}</div>
    </div>"""


def _font_query(theme) -> str:
    """Build the Google Fonts family query for the theme's chosen typefaces."""
    families = []
    for name in (theme.heading_font, theme.body_font):
        if not name or name in families:
            continue
        families.append(name)
    return "&family=".join(f.replace(" ", "+") + ":wght@400;600;800" for f in families)


def build_web_deck(slides_data: list[dict], topic_title: str = "Learnova Interactive Deck",
                   theme_id: str = "auto", theme_spec: dict | None = None) -> str:
    """
    Constructs standalone HTML presentation with Reveal.js and Mermaid.js.
    """
    theme = resolve_theme(topic_title, theme_id, theme_spec)
    # Text drawn on top of the primary fill. Hardcoding white broke every
    # light-primary palette; luminance picks the readable one.
    on_primary = readable_text_hex(theme.primary_hex)

    slides_html_list = []

    # Title slide
    slides_html_list.append(f"""
    <section data-background-color="{theme.bg_hex}" class="title-slide">
        <h1 style="color: {theme.accent_hex}; font-family: '{theme.heading_font}', sans-serif; font-size: 3.8rem; text-transform: uppercase;">
            {html.escape(topic_title)}
        </h1>
        <div style="width: 100%; height: 6px; background-color: {theme.accent_hex}; margin: 20px 0;"></div>
        <h3 style="color: {theme.text_hex}; font-size: 1.5rem;">Generated by Learnova AI Engine • Theme: {html.escape(theme.name)}</h3>
        <p style="color: {theme.subtext_hex}; font-size: 1rem; margin-top: 30px;">Press <strong>Space</strong> or <strong>Right Arrow</strong> to Navigate</p>
    </section>
    """)

    prev_style = None
    for idx, data in enumerate(slides_data, 1):
        orig = data.get("original", {})
        imp = data.get("improved", {})
        if not isinstance(imp, dict):
            imp = {}

        layout_type = imp.get("layout_type", "MINIMAL_TEXT").upper()
        style_pattern = select_slide_layout(idx, layout_type, prev_style)
        prev_style = style_pattern
        title_text = html.escape(imp.get("title", orig.get("title", f"Slide {idx}")))
        takeaway_text = html.escape(imp.get("takeaway", "").strip())

        slide_body = ""

        # ── 1. TABLE LAYOUT ──────────────────────────────────────────────────
        if layout_type == "TABLE" and "table_headers" in imp:
            headers = imp.get("table_headers", [])
            rows = imp.get("table_rows", [])
            th_cells = "".join(f"<th style='background-color:{theme.primary_hex}; color:{on_primary}; padding:12px;'>{html.escape(str(h))}</th>" for h in headers)
            tr_rows = ""
            for r in rows:
                tds = "".join(f"<td style='padding:10px; border-bottom:1px solid #ddd;'>{html.escape(str(val))}</td>" for val in r)
                tr_rows += f"<tr>{tds}</tr>"

            slide_body = f"""
            <div style="overflow-x:auto; margin-top:20px;">
                <table style="width:100%; border-collapse:collapse; background:#fff; box-shadow:0 4px 10px rgba(0,0,0,0.1); font-size:0.85rem;">
                    <thead><tr>{th_cells}</tr></thead>
                    <tbody>{tr_rows}</tbody>
                </table>
            </div>
            """

        # ── 2. METRIC LAYOUT ──────────────────────────────────────────────────
        elif layout_type == "METRIC":
            metric_val = html.escape(str(imp.get("metric_value", "100%")))
            metric_lbl = html.escape(str(imp.get("metric_label", title_text)))
            metric_desc = html.escape(str(imp.get("metric_desc", takeaway_text)))

            slide_body = f"""
            <div style="background:{theme.primary_hex}; border:4px solid {theme.accent_hex}; border-radius:12px; padding:40px; text-align:center; color:{on_primary}; margin-top:20px;">
                <h1 style="font-size:4.5rem; color:{theme.accent_hex}; margin:0;">{metric_val}</h1>
                <h3 style="color:{theme.subtext_hex}; text-transform:uppercase; margin:10px 0;">{metric_lbl}</h3>
                <p style="font-size:1.2rem; color:{on_primary};">{metric_desc}</p>
            </div>
            """

        # ── 3. INTERLEAVED QUIZ LAYOUT ────────────────────────────────────────
        elif layout_type == "QUIZ":
            q_text = html.escape(imp.get("question", "Checkpoint Question"))
            options = imp.get("options", [])
            correct_opt = html.escape(imp.get("correct", "A"))
            explanation = html.escape(imp.get("explanation", ""))

            opt_buttons = ""
            for opt in options:
                opt_str = html.escape(str(opt))
                is_correct = "true" if opt_str.startswith(correct_opt) else "false"
                opt_buttons += f"""
                <button onclick="checkAnswer(this, {is_correct})" style="width:48%; padding:15px; margin:1%; background:#ffffff; border:3px solid {theme.primary_hex}; font-weight:bold; font-size:1rem; cursor:pointer; transition:all 0.2s;">
                    {opt_str}
                </button>
                """

            slide_body = f"""
            <div style="text-align:left; background:#f4f6fb; border-left:6px solid {theme.primary_hex}; padding:20px; border-radius:8px; margin-top:20px;">
                <h3 style="color:{theme.primary_hex}; margin-top:0;">❓ {q_text}</h3>
                <div style="display:flex; flex-wrap:wrap; margin-top:15px;">
                    {opt_buttons}
                </div>
                <div class="quiz-feedback" style="display:none; margin-top:15px; padding:12px; border-radius:6px; font-weight:bold;"></div>
                <p class="quiz-exp" style="display:none; font-size:0.9rem; color:#444; margin-top:5px;">💡 {explanation}</p>
            </div>
            """

        # ── 4. FLOWCHART LAYOUT ───────────────────────────────────────────────
        elif layout_type == "FLOWCHART":
            mermaid_code = imp.get("mermaid_code", "graph TD\n  A[Start] --> B[End]")
            escaped_mermaid = html.escape(mermaid_code)
            bullets = imp.get("bullets", [])
            b_items = "".join(f"<li style='margin-bottom:8px;'>{html.escape(b)}</li>" for b in bullets)

            slide_body = f"""
            <div style="display:flex; gap:20px; text-align:left; margin-top:20px;">
                <div style="flex:1; background:#ffffff; padding:15px; border:2px solid {theme.primary_hex}; border-radius:8px;">
                    <div class="mermaid" style="font-size:0.8rem;">
                        {escaped_mermaid}
                    </div>
                </div>
                <div style="flex:1; font-size:0.9rem;">
                    <h4 style="color:{theme.primary_hex}; margin-top:0;">Process Steps:</h4>
                    <ul>{b_items}</ul>
                </div>
            </div>
            """

        # ── 5. DEFAULT MINIMAL TEXT LAYOUT ───────────────────────────────────
        else:
            bullets = imp.get("bullets", [])
            b_items = "".join(f"<li style='margin-bottom:12px;'>{html.escape(b)}</li>" for b in bullets)
            slide_body = f"""
            <div style="text-align:left; margin-top:20px; font-size:1.1rem; line-height:1.6;">
                <ul>{b_items}</ul>
            </div>
            """

        # Takeaway section
        takeaway_html = f"""
        <div style="background:{theme.primary_hex}; color:{on_primary}; border-left:4px solid {theme.accent_hex}; padding:12px; font-size:0.9rem; margin-top:20px; text-align:left; border-radius:4px;">
            <strong>Key Takeaway:</strong> {takeaway_text}
        </div>
        """ if takeaway_text else ""

        # Slide wrapper
        slides_html_list.append(f"""
        <section data-transition="slide" style="text-align:left;">
            <div style="border-bottom:3px solid {theme.primary_hex}; padding-bottom:10px;">
                <h2 style="color:{theme.primary_hex}; font-family:'{theme.heading_font}', sans-serif; font-size:2.2rem; margin:0; text-transform:uppercase;">{title_text}</h2>
            </div>
            {slide_body}
            {_inline_quiz_html(imp.get("inline_quiz"), theme)}
            {takeaway_html}
        </section>
        """)

    slides_content = "\n".join(slides_html_list)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(topic_title)} – Learnova Interactive Presentation</title>
    <!-- Reveal.js CSS (pinned stable 4.6.1) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.6.1/reveal.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.6.1/theme/white.min.css" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family={_font_query(theme)}&display=swap" rel="stylesheet">
    <style>
        body, .reveal {{
            font-family: '{theme.body_font}', sans-serif !important;
            background-color: #f8f9fc;
        }}
        .reveal h1, .reveal h2, .reveal h3 {{
            font-family: '{theme.heading_font}', sans-serif !important;
        }}
        .reveal .slides {{
            text-align: left;
        }}
    </style>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            {slides_content}
        </div>
    </div>

    <!-- Reveal.js (pinned stable 4.6.1, classic UMD build) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.6.1/reveal.js" crossorigin="anonymous"></script>
    <!-- Mermaid.js (cdnjs UMD standalone build – works in local file:// and data URIs) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js" crossorigin="anonymous"></script>
    <script>
        Reveal.initialize({{
            controls: true,
            progress: true,
            center: true,
            hash: true,
            transition: 'slide', // slide/fade/convex/concave/zoom
        }});

        mermaid.initialize({{ startOnLoad: true, theme: 'neutral' }});

        function checkAnswer(btn, isCorrect) {{
            const parent = btn.parentElement;
            const feedback = parent.parentElement.querySelector('.quiz-feedback');
            const exp = parent.parentElement.querySelector('.quiz-exp');
            
            if (isCorrect) {{
                btn.style.backgroundColor = '{theme.accent_hex}';
                btn.style.color = '#000000';
                feedback.style.display = 'block';
                feedback.style.backgroundColor = '#d4edda';
                feedback.style.color = '#155724';
                feedback.innerHTML = '✅ Correct Answer!';
            }} else {{
                btn.style.backgroundColor = '#ffcccc';
                feedback.style.display = 'block';
                feedback.style.backgroundColor = '#f8d7da';
                feedback.style.color = '#721c24';
                feedback.innerHTML = '❌ Incorrect. Try again!';
            }}
            if (exp) exp.style.display = 'block';
        }}
    </script>
</body>
</html>
"""
